{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spore-minio-server-envs
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStore.name }}
    kind: {{ $.Values.externalSecrets.secretStore.kind | default "SecretStore" }}
  target:
    name: spore-minio-server-envs
    creationPolicy: Owner
    template:
      data:
        config.env: |
          export MINIO_ROOT_USER="{{ `{{ .MINIO_ROOT_USER }}` }}"
          export MINIO_ROOT_PASSWORD="{{ `{{ .MINIO_ROOT_PASSWORD }}` }}"
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: {{ required "clusterName is required. Ensure it's set in values.yaml or via --set." .Values.global.clusterName }}-spore-storage-credentials
        property: root_key
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: {{ required "clusterName is required. Ensure it's set in values.yaml or via --set." .Values.global.clusterName }}-spore-storage-credentials
        property: root_secret
{{- end }}
