{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.sporeStorageUser.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.externalSecrets.sporeStorageUser.secretName }}
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "{{ .Values.externalSecrets.sporeStorageUser.secretName }}"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
        - {{ .Release.Namespace }}
        {{- range .Values.externalSecrets.sporeStorageUser.duplication.namespaces }}
        - {{ . }}
        {{- end }}
  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      name: {{ $.Values.externalSecrets.secretStore.name }}
      kind: {{ $.Values.externalSecrets.secretStore.kind | default "SecretStore" }}
    refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
    target:
      name: {{ .Values.externalSecrets.sporeStorageUser.duplication.targetSecretName }}
      creationPolicy: Owner
      template:
        engineVersion: v2
        data:
          {{- $protocol := include "minio.protocol" . }}
          {{- $url := printf "%s://minio.%s.svc.cluster.local" $protocol .Release.Namespace }}
          AWS_ENDPOINT_URL: {{ $url }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: "{{ `{{ .AWS_ACCESS_KEY_ID }}` }}"
          AWS_SECRET_ACCESS_KEY: "{{ `{{ .AWS_SECRET_ACCESS_KEY }}` }}"
          CONSOLE_ACCESS_KEY: "{{ `{{ .CONSOLE_ACCESS_KEY }}` }}"
          CONSOLE_SECRET_KEY: "{{ `{{ .CONSOLE_SECRET_KEY }}` }}"  
    data:
      - secretKey: CONSOLE_ACCESS_KEY
        remoteRef:
          key: {{ required "clusterName is required. Ensure it's set in values.yaml or via --set." .Values.global.clusterName }}-spore-storage-credentials
          property: user_key
      - secretKey: CONSOLE_SECRET_KEY
        remoteRef:
          key: {{ required "clusterName is required. Ensure it's set in values.yaml or via --set." .Values.global.clusterName }}-spore-storage-credentials
          property: user_secret
      - secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          key: {{ required "clusterName is required. Ensure it's set in values.yaml or via --set." .Values.global.clusterName }}-spore-storage-credentials
          property: user_key
      - secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          key: {{ required "clusterName is required. Ensure it's set in values.yaml or via --set." .Values.global.clusterName }}-spore-storage-credentials
          property: user_secret
{{- end }}
