operator:
  operator:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 500Mi
      limits:
        memory: 256Mi

tenant:
  serversPerPool: 1
  drivesPerServer: 1
  capacityPerDrive: 10G
