monitoring:
  serviceMonitor:
    enabled: false

connectionSecret:
  enabled: true

tenant:
  annotations:
    # This hook must be used in pure Helm environments to ensure CRDs are installed before the tenant.
    helm.sh/hook: post-install
  createRootUserSecret: true
  createUserSecret: true
  capacityPerDrive: 1G
  storageClass: standard
  serversPerPool: 4
  drivesPerServer: 1

externalSecrets:
  enabled: false

istioExtras:
  enabled: false
