operator:
  operator:
    replicaCount: 2
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 500Mi
      limits:
        memory: 512Mi

tenant:
  serversPerPool: 4
  drivesPerServer: 1
  capacityPerDrive: 10G
  env:
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: public
    - name: MINIO_PROMETHEUS_JOB_ID
      value: spore-object-store-minio-job
    - name: MINIO_PROMETHEUS_URL
      value: http://spore-observability-prometheus.monitoring.svc.cluster.local:9090
    - name: MINIO_STORAGE_CLASS_STANDARD
      value: "EC:2"
    - name: MINIO_BROWSER
      value: "on"
