{{- if .Values.testing.enabled }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: test-minio
spec:
  configuration:
    destinationPath: s3://skyral-foundations/db-backups
    endpointURL: http://minio
    s3Credentials:
      accessKeyId:
        name: spore-storage-user
        key: CONSOLE_ACCESS_KEY
      secretAccessKey:
        name: spore-storage-user
        key: CONSOLE_SECRET_KEY
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
{{- end }}
