{{- if .Values.connectionSecret.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-connection-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
data:
  {{- $protocol := include "minio.protocol" . }}
  {{- $url := printf "%s://minio.%s.svc.cluster.local" $protocol .Release.Namespace }}
  SPORE_STORAGE_ACCESS_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  SPORE_STORAGE_SECRET_KEY: ""
  AWS_SECRET_ACCESS_KEY: ""
  SPORE_STORAGE_URL: {{ $url | b64enc }}
  AWS_ENDPOINT_URL: {{ $url | b64enc }}
  AWS_DEFAULT_REGION: {{ "us-east-1" | b64enc }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-connection-secret-patcher
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-secret-patcher-sa
      {{- with .Values.operator.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-connection-secret-patcher
          image: "{{ .Values.connectionSecret.job.image.repository }}:{{ .Values.connectionSecret.job.image.tag }}"
          imagePullPolicy: {{ .Values.connectionSecret.job.image.imagePullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              B64_ACCESS_KEY=$(echo -n "$CONSOLE_ACCESS_KEY" | base64 -w 0)
              B64_SECRET_KEY=$(echo -n "$CONSOLE_SECRET_KEY" | base64 -w 0)

              kubectl \
                -n {{ .Release.Namespace }} \
                patch secret {{ .Release.Name }}-connection-secret \
                -p "{\"data\":{\"SPORE_STORAGE_ACCESS_KEY\":\"$B64_ACCESS_KEY\", \"AWS_ACCESS_KEY_ID\":\"$B64_ACCESS_KEY\", \"SPORE_STORAGE_SECRET_KEY\": \"$B64_SECRET_KEY\", \"AWS_SECRET_ACCESS_KEY\": \"$B64_SECRET_KEY\"}}"
          envFrom:
          - secretRef:
              name: {{ .Values.tenant.userName }}
          - secretRef:
              name: {{ .Release.Name }}-connection-secret
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret-patcher
rules:
  - apiGroups: [""]
    resources:
      - "secrets"
    verbs:
      - "get"
      - "patch"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret-patcher
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-secret-patcher-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-secret-patcher
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret-patcher-sa
{{- end }}
