apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ .Values.tenant.name }}
  namespace: {{ .Release.Namespace }}
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  ## Optionally pass annotations to be applied to the statefulset pods
  {{- with .Values.tenant.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
## If not specified, the Tenant pods will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler

spec:
  image: {{ .Values.tenant.image }}
  imagePullPolicy: IfNotPresent
  imagePullSecret:
    name: {{ .Values.tenant.imagePullSecret }}

  prometheusOperator: {{ .Values.tenant.prometheusOperator }}

  features:
    ## Bucket DNS which would allow `buckets` to be accessible as DNS entries of form
    ## `<bucketname>.minio.namespace.svc.cluster.local`
    bucketDNS: true
    ## Specify a list of domains used to access MinIO and Console
    domains: {}

  users:
    - name: {{ .Values.tenant.userName }}

  ## Configures logging according to: https://github.com/minio/operator/blob/master/docs/tenant_crd.adoc#logging
  logging:
  {{- .Values.tenant.logging | toYaml | nindent 4 }}

  env:
  {{- .Values.tenant.env | toYaml | nindent 4 }}

  buckets:
  {{- .Values.tenant.initBuckets | toYaml | nindent 4 }}

  ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
  podManagementPolicy: Parallel

  ## Secret with credentials and configurations to be used by MinIO Tenant.
  configuration:
    name: {{ .Values.tenant.serverConfiguration.name }}

  ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
  priorityClassName: ""

  ## Mount path where PV will be mounted inside container(s).
  mountPath: /export
  subPath: ""

  ## Service account to be used for all the MinIO Pods
  serviceAccountName: ""

  ## Use a certificate issued by the Kubernetes cluster CA
  requestAutoCert: {{ .Values.tenant.requestAutoCert }}

  liveness:
    httpGet:
     path: /minio/health/live
     port: 9000
     scheme: {{ upper (include "minio.protocol" .) }}
    initialDelaySeconds: 5
    periodSeconds: 30
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3


  readiness:
    httpGet:
      path: /minio/health/ready
      port: 9000
      scheme: {{ upper (include "minio.protocol" .) }}
    initialDelaySeconds: 5
    periodSeconds: 15
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3

  ## Specification for MinIO Pool(s) in this Tenant.
  pools:
    ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
    ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
    ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: {{ .Values.tenant.serversPerPool }}
      ## <TENANT_NAME>-pool-<NUMBER> spore-object-store-pool-0
      name:  pool
      volumesPerServer: {{ .Values.tenant.drivesPerServer }}
      nodeSelector: {}
      tolerations: []
      affinity:
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}

      ## Configure resource requests and limits for MinIO containers
      ## TODO(PF-544): What's an appropriate set of resource requests/limits here?
      resources: {}

      ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this
      ## Pool.
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.tenant.capacityPerDrive }}
          {{- if .Values.tenant.storageClass }}
          storageClassName: {{ .Values.tenant.storageClass }}
          {{- end }}
          {{- if .Values.tenant.volumeName }}
          volumeName: {{ .Values.tenant.volumeName }}
          {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
  {{ range .Values.tenant.extraPools }}
    - servers: {{ required "serversPerPool must be configured for extra tenant server pool" .serversPerPool }}
      name:  {{ required "name must be configured for extra tenant server pool" .name }}
      volumesPerServer: {{ required "drivesPerServer must be configured for extra tenant server pool" .drivesPerServer }}
      nodeSelector: {}
      tolerations: []
      affinity:
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}

      resources: {}

      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ required "capacityPerDrive must be configured for extra tenant server pool" .capacityPerDrive }}
          {{- if .storageClass }}
          storageClassName: {{ .storageClass }}
          {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
{{ end }}
